[package]
name = "egui_error"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.0"
egui = "0.31.0"
egui_kittest = { version = "0.31.0", features = ["eframe", "snapshot", "wgpu"] }
env_logger = "0.11.6"
